2024-04-14 15:58:15 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_DEVELOPER-2053vrqCXgl] (setup)[0m
curl -X GET 'http://localhost:8111/authenticationTest.html?csrf' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: */*'\
-H 'Connection: keep-alive'\
-H 'Authorization: Basic OjEyOTQ0MTg2MjIwMjc0MjA1MjI=' \
-d ''
2024-04-14 15:58:15 INFO [32m pytest tests/backend/test_create_project.py::TestProjectCreateWithInvalidData::test_create_project_with_invalid_ids[Roles.PROJECT_DEVELOPER-2053vrqCXgl][0m
curl -X POST 'http://localhost:8111/app/rest/projects' \
-H 'User-Agent: python-requests/2.31.0'\
-H 'Accept-Encoding: gzip, deflate'\
-H 'Accept: application/json'\
-H 'Connection: keep-alive'\
-H 'Content-Type: application/json'\
-H 'X-TC-CSRF-Token: 88f82812-3848-4ec7-9c0a-1bd1b63d4c39'\
-H 'Cookie: RecentLogin=; TCSESSIONID=5CEA475C9246657AAB95C2004A0BD4D0'\
-H 'Content-Length: 114'\
-H 'Authorization: Basic OjEyOTQ0MTg2MjIwMjc0MjA1MjI=' \
-d '{"parentProject": {"locator": "_Root"}, "name": "measure", "id": "2053vrqCXgl", "copeAllAssociatedSettings": true}' 

2024-04-14 15:58:15 INFO 	RESPONSE:
STATUS_CODE: [31m500[0m
DATA: [31mError has occurred during request processing, status code: 500 (Internal Server Error).
Details: jetbrains.buildServer.serverSide.InvalidIdentifierException: Project ID "2053vrqCXgl" is invalid: starts with non-letter character '2'. ID should start with a latin letter and contain only latin letters, digits and underscores (at most 225 characters).
Error occurred while processing this request.[0m